version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-enterprise-kafka:6.0.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-create-topics:
    image: confluentinc/cp-enterprise-kafka:6.0.0
    depends_on:
      - kafka
    hostname: kafka-create-topics
    command: ["bash", "./create-topics.sh"]
    working_dir: /scripts
    volumes:
      - ./scripts:/scripts

  kafka-stream-app:
    image: kafka-hello-stream
    container_name: kafka-hello-stream
    depends_on:
      - kafka
    restart: always
    volumes:
      - ./jars:/opt
    environment:
      STREAMS_BOOTSTRAP_SERVERS: kafka:9092
      OTEL_SERVICE_NAME: kafka-hello-stream
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_EXPORTER_OTLP_ENDPOINT: https://tempo-us-central1.grafana.net:443
      OTEL_EXPORTER_OTLP_TRACES_HEADERS: authorization=<Base64 Grafana Tempo user:password goes here>
      JAVA_TOOL_OPTIONS: -javaagent:/opt/opentelemetry-javaagent.jar -Dotel.instrumentation.kafka.experimental-span-attributes=true

  kafka-producer-app:
    image: kafka-hello-producer
    container_name: kafka-hello-producer
    depends_on:
      - kafka
    restart: always
    volumes:
      - ./jars:/opt
    environment:
      STREAMS_BOOTSTRAP_SERVERS: kafka:9092
      OTEL_SERVICE_NAME: kafka-hello-producer
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_EXPORTER_OTLP_ENDPOINT: https://tempo-us-central1.grafana.net:443
      OTEL_EXPORTER_OTLP_TRACES_HEADERS: authorization=<Base64 Grafana Tempo user:password goes here>
      JAVA_TOOL_OPTIONS: -javaagent:/opt/opentelemetry-javaagent.jar -Dotel.instrumentation.kafka.experimental-span-attributes=true
